### ISSUE TITLE
Add registration/log in/log out functionality

### ISSUE THREAD

**Issue by ELautzenhiser** [ELautzenhiser/gAImeCompetition#11]
Users need to register and then log in to create players or games.

**Comment by ELautzenhiser** [comment]
Once we have the ability to log in, we should go through the HTML and make sure certain actions (like uploading a player) are disabled if there isn't a logged-in user. We should also make sure we don't assume a user in any of our current code - I'm pretty sure I've assumed g.user['id'] exists at least once.

**Comment by benjaminpjones** [comment]
We can probably add the user checks already, since we get automatically logged in to gaime_admin when the session starts. As far as assuming g.user exists... unit tests!

**Comment by ELautzenhiser** [comment]
Yeah, we can certainly start working on those issues now, but I think it'll be a little easier to catch once we don't have to go in and edit out code to be logged out.

**Comment by ELautzenhiser** [comment]
But if you want to do some of that now, feel free! I'm just working on some other functionality at the moment.

**Comment by ELautzenhiser** [comment]
Functionality added with [commit 137](https://github.com/ELautzenhiser/gAImeCompetition/commit/a34332f85957e05a2bb78b37152b11d24c7b51ae)
