### ISSUE TITLE
game upload should redirect to page with game upon successful upload

### ISSUE THREAD

**Issue by benjaminpjones** [ELautzenhiser/gAImeCompetition#13]
Either the a game preview or "Your Players".  Currently redirects to index, which does not show unpublished games.

Alternatively, we could have a pop-up that says "Go to Your Players to view unpublished games."

**Comment by ELautzenhiser** [comment]
You're right!

**Comment by ELautzenhiser** [comment]
Issue fixed with commit above. Users are now redirected to their games.
