### ISSUE TITLE
Games don't always show up on index

### ISSUE THREAD

**Issue by benjaminpjones** [ELautzenhiser/gAImeCompetition#2]
Games don't show up on the index unless it already has players. That would make it hard for a new game to gain traction (unless this is by design to force admins to create a default player)

**Comment by ELautzenhiser** [comment]
Fixed by [commit 61](https://github.com/ELautzenhiser/gAImeCompetition/commit/042d440d926e8565cd4111cde0b11d2c13c56a71).
