### ISSUE TITLE
Game descriptions should be in the same folder as game referees

### ISSUE THREAD

**Issue by ELautzenhiser** [ELautzenhiser/gAImeCompetition#5]
I think that the new directory structure for UserSubmissions is a little confusing and unwieldy. I think it makes sense to have all documents for a game stored in the same folder as siblings, rather than making them second cousins with a great-grandparent UserSubmissions. I think that's the easiest way to ensure that if one of us wants to look at the code and description side-by-side, we're not going to make any mistakes.

Also, the folder should be more than just a number: it isn't clear whether the trees are stored based on uploading user id or game id. My personal preference would be for game info to be stored by game id.

**Comment by benjaminpjones** [comment]
Is this the structure you're proposing?

* UserSubmissions/
  * Games/
     * Game_1/
        * refbot.py
        * doc.md
     * Game_2/
        * refbot.py
        * doc.md
  * Players/
     * User_1/
        * 8809480257rpsbot.py
        * 0482985750pokerbot.py
     * User_2/
        * 1083948085pokerbot.py
        * 8401840481chessbot.cpp
        * ...

I'm fine with any structure as long as all the user code is in one place. That was my motivation behind creating the UserSubmissions folder.

**Comment by ELautzenhiser** [comment]
Yeah, I think that structure is a lot easier. Let's go with that for now.

**Comment by benjaminpjones** [comment]
We good with this one?

**Comment by ELautzenhiser** [comment]
We good.
